language: android
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

script:
   - ./options/gradlew check
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
